name: Generate and Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install Dependencies 📦
        run: npm ci

      - name: Convert Obsidian Callouts to Hexo Notes 🔄
        run: node scripts_ci/convert.js

      - name: Generate Pages 🚀
        run: npx hexo generate

      - name: Deploy to "html" branch ✈️
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: html
          FOLDER: public
          CLEAN: true
